### ISSUE TITLE
Create custom sidebar

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#1]
The default sidebar in the wiki is not good enough, create a custom sidebar with hierarchy and sorting.

Due date: 9 October

**Comment by dbaslan** [comment]
Created custom sidebar with separate tabs, more pages can be added as we make progress.

**Comment by sadikkuzu** [comment]
Fantastic! ✨
Really cool sidebar, thanks! 🎉🚀
