### ISSUE TITLE
Do research and try to implement area location

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#100]
We are already using Google Maps API to show location. But it's requested to be able to select area on the map. 

Now I will make a research and will try to implement area selection in the project for both backend and frontend. 

**Important Note:**
We should consider which one is more suitable and which one we can use on both web and mobile

**Comment by ckertam** [comment]
First possible selection is [Google Maps API Shapes](https://developers.google.com/maps/documentation/javascript/shapes)

Secondly we may try leaflet directly [Leaflet](https://leafletjs.com/)

**Comment by ckertam** [comment]
After some researches we decided to use Google Maps because it is way easier on web. And have implementation posibilities on mobile too.

**Comment by ckertam** [comment]
<img width="945" alt="image" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/78985396/1397e3bb-d2df-4d1e-9e32-f3883c63edf2">

We can create something like above. 

For now we can create and see stories. 

Search & other implementations will be added soon 🥂

**Comment by sadikkuzu** [comment]
@ckertam You quickly solve whatever is needed. Congrats, you did a great job, well done! Thank you so much ✨ 👏🏼

**Comment by ckertam** [comment]
@SWE574-Fall2023-Group1/all 
Everything done! Need to test it more now. 
Basically users can do belowings now.
- Add every shape of location while creating a story. 
- Can remove them before creating the story. 
- Autocomplete still working so users can make search for locations.
- If users click on a shape in a story the user will see the stories that has a location inside the clicked area
- Line and point clicks return 5km radius area
- In search page users can make search with radius & points.

Need to fix/improve
- For now in search pages markers does not shown we need to handle it. 
- In timeline search we show the location's place. But now if the point is not point we do not show it. Need to handle it too.
- Auto zoom & Auto centerilization not exist for now. Need to discuss where we need them. Then we can implement them

**Comment by ckertam** [comment]
We handled it in the first place. But we need to solve some bugs as I mentioned.

**Comment by ckertam** [comment]
Close commits

7f55043f0dad7041ce5cd3723c459842ffcc1f7f
1bf18ad282c8e8f661beebeb0a03760de00a4c16
d4e449ff8535128d80e43b7257c83b3464efe178
e173e31cb1c404dea9a355169de927bcb77159b6
0511d63271ef7589ab38db8a6649f581f22d0a61
6f1bfdf42c73d4fe09cb7e82790290df1e552d40
966a16b206af3360e22113281437e5b5bc04ef1a
f75dd9f707fab87ee961632a6601a755eeb16471
8b067989152a8e4cf9d92221705a762f3040b0b6
6afe008832adb05fd1ee141478b04075e6d60dc9
1cfd9603f1d7a4a737ce0586c0d2946dd07ecccb
