### ISSUE TITLE
Migration file for new `StoryImage` model

### ISSUE THREAD

**Issue by sadikkuzu** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#110]
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/blob/cd40dcecb37af5a6d169987d05bdbdc7e635a0ef/backend/user/models.py#L27-L28

We have new StoryImage model.
Then now, we need to run

```
python manage.py makemigrations
```

in `backend` folder
in order to get `./user/migrations/0029_storyimage.py`.

**Comment by ckertam** [comment]
Issue will resolved with new branch #100
