### ISSUE TITLE
Create better pop-up messages

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#112]
@SWE574-Fall2023-Group1/frontend  The professor didn't like how our pop-up error messages looked during the presentation. Let's fix them for the web app, and design them for mobile as well.

Due Date: Milestone 2 Presentation

**Comment by oguzsenna** [comment]
Mobile mockup file:
https://www.figma.com/file/uYsmFIA0eHKg63wWICI326/574-UI-KIT?type=design&node-id=2124%3A9969&mode=design&t=k7FTWQQxlMN32MRa-1

Web mock-up file:

https://www.figma.com/file/8zYkdrtzVFm5CJ3rRqLUZs/574-WEB?type=design&node-id=0%3A1&mode=design&t=4peFUAyr5RkfSrwR-1

**Comment by ckertam** [comment]
On web we are done with this! On mobile @oguzsenna will open a new issue in that project
