### ISSUE TITLE
Add actions for enter key

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#113]
@SWE574-Fall2023-Group1/frontend The web app responds to button clicks but not to the enter key being pressed, at least not for all entry forms. Let's make sure the enter key has the same function as the confirmation buttons.

Due Date: Milestone 2 Presentation

**Comment by sadikkuzu** [comment]
@dbaslan hi,
Register and Login pages do not respond to the enter key.
Could you please check them and other pages out again?
Thanks in advance.

**Comment by oguzsenna** [comment]
homepage search bar works like the following:
1- Write down the username, if it finds usernames it lists them under the input area.
2- Click on the username 
3- Click the search button
