### ISSUE TITLE
Redesign profile page

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#151]
Profile page should be designed as mockup below: 

<img width="682" alt="Screenshot 2023-11-19 at 14 50 09" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/126410955/0cff4a6d-2f6c-4c7d-953b-0cbe7e6a2b3d">

**Comment by sadikkuzu** [comment]
Will there be [upload/change/remove profile photo ](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/issues/101)button(s)?
And also, followers count info?

![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/0c6979f2-a4c0-42ae-9451-2b2d011a0e99) ![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/c3fc15a4-e4ba-4cc5-9159-1c72f4076e30)

**Comment by aykutkantas** [comment]
Great job! I have added them and finally it's something like that :) 

<img width="679" alt="Screenshot 2023-11-21 at 23 12 57" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/126410955/4e92bc51-81f4-408e-9cd7-20d12fddb0f7">

**Comment by sadikkuzu** [comment]
wow! stunning design 👏🏼🤩

**Comment by ckertam** [comment]
It is perfect! 👏

**Comment by aykutkantas** [comment]
I also added username. This is better I think. 

<img width="674" alt="Screenshot 2023-11-21 at 23 49 53" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/126410955/9c4edd77-e84e-496f-b8e3-d59870fdfebe">

**Comment by sadikkuzu** [comment]
ooo niceee
then now on, we can sell blue-tick to our users that want to be priviliged:))
