### ISSUE TITLE
Timeline Design Imps

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#153]
On frontend we need to improve our timeline design. There will be a slider that shows story's photo bigger if the story is the middle side of slider. 

For milestone 2 we only need to show stories on a slider but slider does not need to work for milestone 2. 

@aykutkantas will add design of timelien slider.

**Comment by sadikkuzu** [comment]
Done
and also fixed by #233
