### ISSUE TITLE
Fix login page scaling

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#163]
In register page when we make the web browser window smaller the login part does not scale according to that. Below you can find examples. Although  the navbar scales correctly. Can we solve it? or should we solve it?

**Full sized web browser**
<img width="1461" alt="image" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/78985396/34a41967-ff0e-4115-a1bc-32e4724e39d8">
**Not full sized web browser (on the left side)**
<img width="688" alt="image" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/78985396/f52dea1b-5432-437a-9cc7-c2bb6cb0f1de">
**Not full sized web browser (on the right side)**
<img width="687" alt="image" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/78985396/55f311a6-9f98-40b6-99df-0a872a9e05aa">

**Comment by sadikkuzu** [comment]
@aykutkantas hi,
Are you on it?

**Comment by aykutkantas** [comment]
@sadikkuzu yes I am working on it :)

**Comment by dbaslan** [comment]
On it!

**Comment by dbaslan** [comment]
Opened pull request #280, awaiting approval to merge.

**Comment by dbaslan** [comment]
Merged branch, closing.
