### ISSUE TITLE
Documentation for local frontend development

### ISSUE THREAD

**Issue by sadikkuzu** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#184]
As frontend team
we want to run npm start, instead of docker compose up everytime,
so that we will be able to get frontend implementations' results rapidly.

**Comment by sadikkuzu** [comment]
@dbaslan could you please test these command lines above?

**Comment by sadikkuzu** [comment]
Done w/ https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/185#pullrequestreview-1759134331

**Comment by dbaslan** [comment]
It works, thank you! This will make our work three times as fast 😎 
![artworks-000209301625-1gtat4-t500x500](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/66262500/8f76fa9e-751c-4234-9dda-18561ee7eecc)
