### ISSUE TITLE
Check docker versions on VM

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#195]
We noticed that some docker-compose.yml file changes effect dockerization. 

There is an issue and it might be caused by version system. So let's check it

**Comment by sadikkuzu** [comment]
https://docs.docker.com/engine/install/debian/#upgrade-docker-engine-1

```shell
sudo su -
cd
curl -fsSL https://get.docker.com -o get-docker.sh
sh ./get-docker.sh
```

![upgrade-docker](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/8aeba79b-57ed-40e8-9a6d-89b811525f25)
