### ISSUE TITLE
Create repository for mobile development 

### ISSUE THREAD

**Issue by oguzsenna** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#20]
* [x] Create a new repository for mobile
* [x] Add Flutter specific .gitignore file
* [x] Construct pre-commit mechanism
* [x] Add the professor as a collaborator

**Comment by sadikkuzu** [comment]
Repo is ready: https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile

And this issue is ready for review. @oguzsenna

**Comment by sadikkuzu** [comment]
@SWE574-Fall2023-Group1/mobile
