### ISSUE TITLE
Fix author profile pic in memory detail

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#201]
In memory detail we should see author profile picture, instead we see logged-in user profile picture.

**Comment by sadikkuzu** [comment]
Thanks @ckertam ✨ 
Really cool improvement! 🚀 👏🏼 

before:

![before](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/42d52358-13ed-49b6-a31a-93e84a55bd3c)


after:

![after](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/66bf73ad-30c1-419f-b218-737411c441b7)
