### ISSUE TITLE
Fix frontend fonts

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#240]
Can you decide a font & also make some changes on font sizes etc in all pages.

@oguzsenna

**Comment by oguzsenna** [comment]
<img width="294" alt="Screenshot 2023-12-10 at 20 00 46" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/93736051/2f8eba5d-f68c-48ed-9960-96ab7b3496a4">

I Found a pretty font, you can see from the above example.

I want to implement it to the areas:

- Navbar
- Page Main titles
- Texts inside the buttons

WDYT ?

**Comment by sadikkuzu** [comment]
Looks amazing! 🤩

**Comment by dbaslan** [comment]
Looks cool

**Comment by oguzsenna** [comment]
Approved, thanks for improvement :)

**Comment by dbaslan** [comment]
Merged branch, closing issue.
