### ISSUE TITLE
Make sure the updateStory endpoint converts the error message to string

### ISSUE THREAD

**Issue by sadikkuzu** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#247]
The updateStory endpoint can return a list of error messages in some cases.

In the scope of this task, the error messages will all be in string format.

**Comment by ckertam** [comment]
Handled by @sadikkuzu and tested by me @ckertam

**Comment by sadikkuzu** [comment]
Kudos to @ckertam 🎊 
He indicated the actual code lines, and obviously tested the endpoint responses.
Thanks again 🙏🏼
