### ISSUE TITLE
Fix following stories font

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#282]
As I see @dbaslan changed the fonts in AllStories but in FollowingsStories part it is still the same. Why didn't we implement it?

**Comment by dbaslan** [comment]
On it!

**Comment by dbaslan** [comment]
Awaiting approval for pull request #289

**Comment by sadikkuzu** [comment]
@dbaslan hi,
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/289#issuecomment-1859135655 & https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/289#issuecomment-1859135932

**Comment by dbaslan** [comment]
Turns out I missed a few more instances, thank you @sadikkuzu 🙏 Awaiting approval

**Comment by dbaslan** [comment]
Merged branch, closing
