### ISSUE TITLE
Implement frontend pop-up warnings

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#285]
- When a user tries to submit or send a request and the response is an error, there is no pop up information to explain the error.

Except login & register pages

**Comment by dbaslan** [comment]
Created branch, let's go team @SWE574-Fall2023-Group1/frontend

**Comment by dbaslan** [comment]
I added popup messages to memory creation and memory editing. Anywhere else where we need popups?

**Comment by dbaslan** [comment]
Merged branch, closing.
