### ISSUE TITLE
Organize and revise requirements

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#29]
Making groups for functional requirements such as Profile, Search, User's Stories etc. 
Revising some requirements according to comments of professor on Monday 16/10/2023, such as eliminating some words regarding design (button, page, click etc.) from requirements and some improvements on sentences.

**Comment by aykutkantas** [comment]
These revisions have been made. Functional requirements have been grouped. Some design statements have been eliminated and also some requirement sentences have been improved according to professor's comments.

**Comment by dbaslan** [comment]
We got more feedback from the professor, will need to rework further. Moved back to "In progress".

**Comment by aykutkantas** [comment]
Notes of last class have been added to requirements ideas page.

**Comment by dbaslan** [comment]
Revised requirements based on most recent feedback, please check and confirm @SWE574-Fall2023-Group1/all

**Comment by aykutkantas** [comment]
They are ok, thanks
