### ISSUE TITLE
Write final milestone report

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#295]
@SWE574-Fall2023-Group1/all I'll share the HackMD link and invite everyone. It might be a bit early but let's start writing the final report.

**Comment by dbaslan** [comment]
Invited everyone and shared the link. Please read the specifications pdf beforehand, the instructions are not the same as the previous two.

**Comment by sadikkuzu** [comment]
Completed with great efforts by the team ✨ 🚀
