### ISSUE TITLE
Improve timeline response formatting

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#297]
We need to format search as timeline results "search parameters". 
<img width="1460" alt="image" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/78985396/538e0d30-7f7e-4b5c-9bdc-4b5b963c6e42">

Also let's remove "TIMELINE" header. 

You can do the necessary things inside the "Timeline.js"

**Comment by dbaslan** [comment]
Moved a few things around, could you specify what else you'd like @ckertam?

![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/66262500/5ffd62f7-6607-4d0f-a454-9e85e3b5552c)

**Comment by dbaslan** [comment]
Merged, closing issue.
