### ISSUE TITLE
Create design diagrams

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#298]
We need updated design diagrams for the final report. Class diagrams or use case diagrams might be best.

Due Date: Final Milestone Submission

**Comment by dbaslan** [comment]
Do we have anything ready? @ckertam

**Comment by dbaslan** [comment]
We decided not to include these, closing as not planned.

**Comment by sadikkuzu** [comment]
System Design Diagram

![system-design](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/5a7ad067-7026-43e0-810f-59ef3ba3d346)

**Comment by dbaslan** [comment]
Thank you for the diagrams!
