### ISSUE TITLE
Create custom footer

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#3]
The wiki does not have a footer, create a custom one.

Deadline: 16 October

**Comment by sadikkuzu** [comment]
Custom footer is ready for review 👀 
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki

**Comment by dbaslan** [comment]
Thank you, looks great! 😀
