### ISSUE TITLE
Clean up issues and pull requests

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#300]
Some of our issues have formatting errors or missing descriptions. Proofread and fix everything, including the mobile repo and pull requests.

Due Date: Final Milestone Submission

Task Lead: @sadikkuzu

**Comment by sadikkuzu** [comment]
## Search queries

### G1 repo

* https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/issues?q=no%3Aassignee
* https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/issues?q=no%3Alabel
* https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/issues?q=no%3Amilestone


### G1-mobile repo

* https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/issues?q=no%3Aassignee
* https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/issues?q=no%3Alabel
* https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/issues?q=no%3Amilestone

### Issues w/o Project info

Only issues should have a project card. It doesn't have to be in pull-requests.

* https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/issues?q=is%3Aissue+no%3Aproject
* https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/issues?q=is%3Aissue+no%3Aproject

#### References

* https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests
* https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-missing-metadata

**Comment by sadikkuzu** [comment]
The queries listed above should return empty resultset in the end.

**Comment by dbaslan** [comment]
Thanks for the queries @sadikkuzu, all done. Moving on to descriptions and proofreading.

**Comment by dbaslan** [comment]
All issues have descriptions now. Keeping the issue open for remaining tasks.

**Comment by sadikkuzu** [comment]
Great job! Thank you so much @dbaslan 🚀

**Comment by dbaslan** [comment]
Proofreading is over, closing issue.
