### ISSUE TITLE
Create Web Application Mockups

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#31]
Creating sign up, login, sign out, feed, profile pages mockups.

**Comment by aykutkantas** [comment]
https://www.figma.com/file/8zYkdrtzVFm5CJ3rRqLUZs/Untitled?type=design&node-id=0%3A1&mode=design&t=R6r8J4Y1voApq4Zt-1

**Comment by ckertam** [comment]
Can we get edit perm? If anybody @SWE574-Fall2023-Group1/all needs it please give your e mail to get edit perm.

My e mail: ckertam9696@gmail.com

And do we have any progress since last updates

**Comment by ckertam** [comment]
Also it will be good if we can finish them until first milestone report. So we may put them as we will update our web part as mockups. It will be a nice plan for the professor I guess 😄

**Comment by aykutkantas** [comment]
web mockups for milestone 1 have been finished. [https://www.figma.com/file/8zYkdrtzVFm5CJ3rRqLUZs/Untitled?type=design&node-id=0-1&mode=design&t=M0ScHAFz99MBzpPF-0]

**Comment by ckertam** [comment]
Very nice! @aykutkantas if it is finished can you move the figma link to #68

**Comment by aykutkantas** [comment]
Figma link has been added to #68. Team also has been created and edit authorized for everyone.
