### ISSUE TITLE
Upload file size issue

### ISSUE THREAD

**Issue by mert-aydin** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#313]
When changing profile picture by taking a new pic from camera, the file created is usually larger than the backend allows. Limit for the file size should be increased.

Also, an appropriate error message should be displayed if upload file size is exceed.

**Comment by ckertam** [comment]
I created an env variable for this named 

"MAX_FILE_SIZE_IN_BYTES" so we can change it easily
