### ISSUE TITLE
Record Demonstration Videos

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#315]
We need to record and submit at least one video with our final submission. One video for mobile and one video for web should be enough to demonstrate our features. I can upload them as unlisted videos on YouTube. Of course, we have to make the release first.

Due Date: Final Report Submission

**Comment by dbaslan** [comment]
@aykutkantas is recording a video for the web app and I will record one for the mobile app. @SWE574-Fall2023-Group1/mobile Please let me know when we have an apk with the final features of the app.

**Comment by sadikkuzu** [comment]
> @aykutkantas is recording a video for the web app and I will record one for the mobile app. @SWE574-Fall2023-Group1/mobile Please let me know when we have an apk with the final features of the app.

@dbaslan hi,
For mobile apk, you can use this app release:
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/actions/runs/7292959059

**Comment by dbaslan** [comment]
@aykutkantas You can send me the video when you're done, I'll take care of the rest.

**Comment by aykutkantas** [comment]
@dbaslan web demo video has been created in this link. https://drive.google.com/drive/folders/1HzE1NcJXvMx0Xaprk3bjsuOD1TyWERfA?usp=sharing

**Comment by dbaslan** [comment]
Videos have been recorded, edited and uploaded to YouTube. Closing issue.
