### ISSUE TITLE
Commits, Branching and Pull Requests Conventions

### ISSUE THREAD

**Issue by sadikkuzu** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#32]
There are some TBD parts in Conventions wiki.
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Conventions#commits

In this task; Commits, Branching and Pull Requests parts will be improved.

**Comment by ckertam** [comment]
If we're done with this issue can we close it? @sadikkuzu

**Comment by sadikkuzu** [comment]
Well, not yet actually.
I'll finish it tonight.

**Comment by sadikkuzu** [comment]
[Commits](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Conventions#commits), [Branching](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Conventions#branching) and [Pull Requests](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Conventions#pull-requests) Conventions are 🆗 🚀
