### ISSUE TITLE
[HomePage] Put some space above the logo

### ISSUE THREAD

**Issue by sadikkuzu** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#321]
Is it possible to put some space above the logo?

![welcome-page](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/afd471ed-1a9d-4db1-80db-7239ebe07631)

_Originally posted by @sadikkuzu in https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/discussions/245#discussioncomment-7928231_

**Comment by dbaslan** [comment]
On it!

**Comment by dbaslan** [comment]
Awaiting approval at #323

**Comment by dbaslan** [comment]
Merged, closing issue.
