### ISSUE TITLE
Reduce "Create New Memory" button font-size

### ISSUE THREAD

**Issue by sadikkuzu** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#322]
I think "Create New Memory" button has big font-size for the page it's on.
We may reduce its value or remove it completely.

before:
![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/e3e76a0f-8bce-4ae4-9f12-a12c148c2369)

after:
![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/9484c64d-4fbc-4aa8-bdb3-2fdf77f38b23)

_Originally posted by @sadikkuzu in https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/discussions/236#discussioncomment-7772203_

**Comment by dbaslan** [comment]
On it!

**Comment by dbaslan** [comment]
Branch created, see #321

**Comment by dbaslan** [comment]
Awaiting approval at #323

**Comment by dbaslan** [comment]
Merged, closing issue.
