### ISSUE TITLE
Time Edit Runtime Error

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#328]
I get the "Cannot read properties of null (reading 'slice')" error whenever I try to edit a memory and choose normal date or interval date. (i.e. the options that bring up the "include time" option) The error does not occur in memory creation, only in edit mode. Can we fix this? @SWE574-Fall2023-Group1/frontend  

![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/66262500/a0aae836-85c0-4721-ba85-2f2d0e7a88f6)

Due Date: Final Report Submission

**Comment by ckertam** [comment]
This is a frontend issue but I will handle it :)

**Comment by dbaslan** [comment]
Sorry about that, thanks 😅

**Comment by ckertam** [comment]
I also resolve the time localization issue :)
