### ISSUE TITLE
Create Scenarios for Milestone 1

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#38]
We need to create at least one user scenario for the milestone presentation on 30 October. One scenario could cover all deliverables for web, another could cover mobile.

**Comment by dbaslan** [comment]
I created two scenarios, one for mobile and one for web, which follow one another. Please take a look to confirm, make sure I didn't mention any features that we haven't added yet. @SWE574-Fall2023-Group1/all

**Comment by sadikkuzu** [comment]
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/User-Scenarios

**Comment by oguzsenna** [comment]
User scenarios are added to the wiki. I checked and it looks good.
