### ISSUE TITLE
Improve Main Page Story Preview

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#39]
Improve the main feed story preview like below mockup. 
Sort according to creation date
![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/78985396/1d541622-78b6-464d-aea2-c4d66d3c6b82)

**Comment by sadikkuzu** [comment]
Is it possible to crop the image above?

**Comment by ckertam** [comment]
Done 👍

**Comment by ckertam** [comment]
Already related with #68 so closing this issue
