### ISSUE TITLE
Refine frontend code

### ISSUE THREAD

**Issue by oguzsenna** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#42]
As a frontend developer, I want to enhance web frontend codebase so that a fluent UX will be created.

**Comment by sadikkuzu** [comment]
Hi @oguzsenna 
Too general task, let's change title and description
with respect to "Display notification if signup is ok" commit message
and then let's close this issue.

**Comment by dbaslan** [comment]
We have opened several issues for rehauling the frontend and are working on it. @oguzsenna can you merge your branch so we can close the issue?

**Comment by sadikkuzu** [comment]
@oguzsenna @dbaslan hi,
is it ok to close this task now?

**Comment by ckertam** [comment]
I guess we can close this issue we do not need to do that we are already updating the frontend codes!
