### ISSUE TITLE
Get on the same page

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#44]
@SWE574-Fall2023-Group1/all Folks we need to get on the same page so there are no misunderstandings, especially so the professor won't catch us off-guard during the milestone presentation. Can everyone please: 

 - Star and follow the repo
 - Read through the wiki (especially the conventions)
 - Read the final version of the requirements (still working on them 😅 )
 
We need to keep the documentation consistent. We'll also need to agree on the requirements, let's discuss this in the next regular meeting.

Due date: 29 October

(Issue opened per popular demand)

**Comment by sadikkuzu** [comment]
what is pre-commit? and what are the use cases?
[![asciicast](https://asciinema.org/a/WVfOHTzVzxzoujuUenCwjGrL2.svg)](https://asciinema.org/a/WVfOHTzVzxzoujuUenCwjGrL2)

**Comment by ckertam** [comment]
What is update here? I guess we have another related issue with this. #40 ? @dbaslan

**Comment by dbaslan** [comment]
We have the [updated requirements](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Requirements) along with a glossary now, everyone should read them before our regular meeting this week, we'll discuss everything then.

**Comment by dbaslan** [comment]
Discussed everything in [regular meeting 2](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/2023%E2%80%9010%E2%80%9028-Regular-Meeting-2), we are now on the same page. Closing.

[REQUIREMENTS REQUIREMENTS REQUIREMENTS](https://www.youtube.com/watch?v=Vhh_GeBPOhs)
