### ISSUE TITLE
Hold first frontend meeting

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#47]
@SWE574-Fall2023-Group1/frontend The frontend team needs to meet up online to finish the mockups, discuss the branching and start pushing to dev branch. Let's set up a meeting.

Due date: 29 October

**Comment by oguzsenna** [comment]
I am available midnights throughout the week

**Comment by dbaslan** [comment]
I am available all week long, except Friday 19 - 22 PM

**Comment by aykutkantas** [comment]
I am also available all week long, except class hours (Wednesday and Thursday 7-10 pm)

**Comment by ckertam** [comment]
Okay the meeting will be hold on Thursday (26 October) at 22:00 maybe after class if we all have the same lesson. @SWE574-Fall2023-Group1/frontend

**Comment by dbaslan** [comment]
Thanks for coming folks 👍
