### ISSUE TITLE
Create new issue labels

### ISSUE THREAD

**Issue by oguzsenna** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#5]
We need new labels for new types of tasks such as team assignment or decision making.

Create these issue labels

Due date: 16 Oct 2023

**Comment by oguzsenna** [comment]
Can you give example guys ? @SWE574-Fall2023-Group1/all

**Comment by dbaslan** [comment]
Discussion or decision-making for issues that have to do with management
Maybe something like "preparation" for tasks that are neither coding nor documentation (setting meetings, finding a resource, etc.)
Deployment for the deployment team's tasks
Research for tasks that have to do with finding information and explaining tools on the wiki
That's all I can think of right now

**Comment by oguzsenna** [comment]
Discussion, Preparation, Deployment, Research sound nice. 
We can add them.

Let's keep the issue open in case of new ideas.

**Comment by dbaslan** [comment]
Added the new issue labels for discussion decision-making and planning, closing issue. New labels can still be added in the future.
