### ISSUE TITLE
Change profile photo response and requests

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#56]
Need to change profile photo response and requests in both frontend & backend for response convention

**Comment by sadikkuzu** [comment]
Done with https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/57

Commits:
* Change profile photo get response on backend https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/57/commits/e65499775e24648237974ab17ceb69bb119b5b2f
* Made adjustments on frontend for profile photo request responses https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/57/commits/c90deb9e5653a485bc2bb8ce78568317d0ef9ef8
