### ISSUE TITLE
Get milestone report template

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#58]
Ask the professor to share the milestone report template so we can get started with the report.

Due date: 25 October

**Comment by dbaslan** [comment]
Asked on Discord, awaiting response.

**Comment by sadikkuzu** [comment]
https://swe574-fall2023-group1.github.io/docs/Swe574_2023_Fall_M1_Deliverables.html
