### ISSUE TITLE
Clean up Requirements 

### ISSUE THREAD

**Issue by oguzsenna** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#6]
Requirements are not formatted properly and there are typos. 

Clean and format them

Due date 16 Oct 2023

**Comment by dbaslan** [comment]
Formatted the requirements, will proofread and number them before the lecture

**Comment by dbaslan** [comment]
Cleaned up the requirements, removed duplicates and numbered correctly. Closing now since the initial version is ready, but requirements are still subject to change.
