### ISSUE TITLE
Write milestone 1 report

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#64]
@SWE574-Fall2023-Group1/all We need to write the first milestone report and upload it to our repo as an .md file. Instructions are available on the wiki under "Documents". I created an .md file on HackMD, I'll invite everyone and we can write it online collaboratively. Will share link on WhatsApp and Discord. Let me know if you have other suggestions.

Due Date:
Pre-release of the software (30.10.2023, 17:00), other deliverables (02.11.2023,17:00).

**Comment by dbaslan** [comment]
Please sign up to HackMD and send me your user information on WhatsApp or Discord so I can invite everyone.

**Comment by dbaslan** [comment]
Integrated HackMD to our repo. Now the [report](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/blob/main/reports/m1_group1.md) can be pushed/pulled directly instead of manual uploads. Let's do it this way, no need to edit the report manually on the repo.

**Comment by sadikkuzu** [comment]
@dbaslan Let's integrate _HackMD_ with `reports` branch.
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/tree/reports

**Comment by dbaslan** [comment]
The report is now integrated with the `reports` branch, and everyone has been invited to write as of yesterday. Let's get this bread folks!

**Comment by oguzsenna** [comment]
I filled up the hack.md file for my part. Good work everyone.

**Comment by dbaslan** [comment]
The report is almost finished. I wrote the milestone review, deliverables and addressed requirements. Please read over them to add anything missing or fix mistakes.

**Comment by sadikkuzu** [comment]
@dbaslan hi,
I've completed my individual-contributions part.
Could you please push the file from HackMD to GitHub?
Thanks in advance 🙏🏼

**Comment by sadikkuzu** [comment]
@dbaslan hi again,
[Responsibility Assignment Matrix](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Responsiblities) link has an empty wiki page result.
Could you please edit that page?
Thanks.

https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Responsiblities
![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/9f34f18b-dd34-42b3-9cf6-0765f6900283)

**Comment by sadikkuzu** [comment]
Thanks everyone @SWE574-Fall2023-Group1/all ✨ 👏🏼 

https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/blob/main/reports/m1_group1.md
[![GitHub G1-milestone1 details](https://img.shields.io/github/milestones/progress/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/2?label=G1-milestone1)](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/milestone/2) [![GitHub G1-mobile-milestone1 details](https://img.shields.io/github/milestones/progress/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/1?label=G1-mobile-milestone1)](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/milestone/1)

![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/c44d9ff9-b625-4c38-ae62-cea10246ee6a)
