### ISSUE TITLE
Recommendation System Ideas

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#67]
How should we show recommendations? 

When do we need to show recommendation? 

Lets give some ideas for recommendation system please @SWE574-Fall2023-Group1/all attend the discussion and propose your idea about recommendation logic. So that we can decide a common idea for all of us 💯

**Comment by sadikkuzu** [comment]
Dear @SWE574-Fall2023-Group1/all 
What is our latest recommendation model/ruleset?

Btw
As professor indicated last Monday (that issues have their own scope), let's close this discussion issue @ckertam
and transfer it and its content into [Discussions](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/discussions).

Let's go on there.

**Comment by dbaslan** [comment]
We're moving to discussion page #149 , closing issue. See you there 👋
