### ISSUE TITLE
Improve frontend design

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#68]
We are already creating a new frontend design. Let's implement it to project. 

[Mockups](https://www.figma.com/file/8zYkdrtzVFm5CJ3rRqLUZs/Untitled?type=design&node-id=0%3A1&mode=design&t=R6r8J4Y1voApq4Zt-1)

#31 

And related issue with this issue #39, #41

**Comment by aykutkantas** [comment]
https://www.figma.com/file/8zYkdrtzVFm5CJ3rRqLUZs/Untitled?type=design&node-id=0%3A1&mode=design&t=R6r8J4Y1voApq4Zt-1

**Comment by ckertam** [comment]
@aykutkantas & @dbaslan you should decide which components will be done by who. 
As I know Aykut created mock ups for this issue. #31

Let's break down components 
Main component groups are below
- [ ] homepage
- [ ] landing
- [ ] profile
- [ ] search
- [ ] story
- [ ] header

**Comment by ckertam** [comment]
Also related with #63

**Comment by sadikkuzu** [comment]
> @aykutkantas & @dbaslan you should decide which components will be done by who. As I know Aykut created mock ups for this issue. #31
> 
> Let's break down components Main component groups are below
> 
> * [ ]  homepage
> * [ ]  landing
> * [ ]  profile
> * [ ]  search
> * [ ]  story
> * [ ]  header

Hi guys,
Is there a final decision about "which components will be done by who"?

If so, let's indicate here and let's close this issue.

If not, let's transfer this content into [Discussions](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/discussions) and again let's close this issue.

Thanks in advance.

**Comment by sadikkuzu** [comment]
@dbaslan

**Comment by aykutkantas** [comment]
@sadikkuzu @dbaslan @oguzsenna I have made landing and also I am planning to make homepage and profile.

**Comment by dbaslan** [comment]
I will be handling the memory creation screen, memory viewing screen and the search screen. @oguzsenna will be handling the timeline, activity stream and the header. We might need to collaborate on search and timeline but we'll see. Closing issue and opening new issues for individual tasks.
