### ISSUE TITLE
Proofread and fix typos

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#69]
The wiki and issues are filled with typos and minor errors. Proofread everything regularly to fix them.

Due date: end of project

**Comment by sadikkuzu** [comment]
I've done proofread and fixed a [tiny little](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Requirements/_compare/c63419e3fe37adbbcaf56ddd4d99b694c71ab10e...b3b5b44a3e8210a02a342ebf3db7b894579352ca) typo.

**Comment by sadikkuzu** [comment]
As the professor indicated last Monday (that issues have their own scope), let's close this general-scope issue @dbaslan 
If it is needed in a way, let's transfer it and its content into [Discussions](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/discussions).

**Comment by sadikkuzu** [comment]
@dbaslan

**Comment by dbaslan** [comment]
Closing issue, will keep proofreading and fixing typos in the future 👍
