### ISSUE TITLE
Create additional design documents and plans

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#71]
The milestone deliverables in the [instructions](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/blob/main/Documents/Swe574_2023_Fall_M1Deliverables_.pdf) list additional items we have yet to create:

- [x] #78
- [x] Project Plan
- [x] Responsibility Assignment Matrix
- [x] Software Design Documents (e.g. diagrams)
- [x] Weekly Reports

I will take care of the communication and project plan, would like to get some input as well. The responsibility assignment matrix might not be necessary but we'll discuss it in the meeting. As for the design documents, @ckertam could you provide any UML diagrams relating to the architecture, class diagrams and such? I'll upload them to the repo and add the to the wiki. We don't have weekly reports, shall we start working on them or not? Will discuss in meeting. @SWE574-Fall2023-Group1/all 

Due Date: 30 October

**Comment by dbaslan** [comment]
Communication plan uploaded to wiki, see #72.

**Comment by ckertam** [comment]
You can find UML diagrams on my project if we need it today. Otherwise I can provide it saturday or sunday. 
[My old project](https://github.com/ckertam/SWE573_SPRING_2023/blob/main/deliverables/Swe573%202023%20Spring-%20FinalProjectReport-KemalCanerErtam.pdf)

**Comment by dbaslan** [comment]
Project plan in the works thanks to @aykutkantas , see #74.

**Comment by dbaslan** [comment]
Responsibility assignment matrix also in the works, will discuss in meeting. See #73.

**Comment by dbaslan** [comment]
Diagram added, see #84.

**Comment by dbaslan** [comment]
We decided in the meeting to not write weekly reports, as the Kanban board and the weekly meeting notes already reflect our progress. This addresses all the new documents we need, closing.
