### ISSUE TITLE
Project Plan for Milestone 1 Report

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#74]
We need a project plan to show milestones and deliverables for using in milestone 1 report

**Comment by aykutkantas** [comment]
[SWE574 Group 1 Project Plan.xlsx](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/files/13191620/SWE574.Group.1.Project.Plan.xlsx)

We can use this document for showing deliverables of each milestones and their progress. I entered dates and progress for milestone 1, we can update together and also we can enter for other milestones too.

**Comment by dbaslan** [comment]
Looks great, thanks! Let's go over it in the meeting to confirm and we'll add it to the report as well 👍

**Comment by dbaslan** [comment]
Reviewed the plan in the meeting, will upload to wiki as well. We can edit it in the future once milestones are clearer, closing.
