### ISSUE TITLE
Implement user acceptance tests

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#79]
We need to create user acceptance test scenarios and implement them.

Due Date: Milestone 2 Presentation

**Comment by sadikkuzu** [comment]
Hi @aykutkantas 
Are UATs ready for run?

**Comment by aykutkantas** [comment]
User acceptance test scenarios are created [here](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/UAT-Cases)
We can add more.
