### ISSUE TITLE
Unit test execution

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#80]
Unit test creation and execution

**Comment by sadikkuzu** [comment]
Do we have unit test in codebase? @aykutkantas

**Comment by sadikkuzu** [comment]
@aykutkantas hi,
Did you create unit tests and do executions?

If not, could you please change task milestone to "Final Milestone"?
Thanks in advance.

![unit-test-execution](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/d339a85c-fe7b-4476-9282-aba42920934f)

**Comment by sadikkuzu** [comment]
I redesigned App.test.js unit test and fixed Login.test.js unit test.
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/pull/254#pullrequestreview-1773861301
