### ISSUE TITLE
Follow user button & counter issue

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#81]
When I follow a user the counter does not change. 

Also, if I am following a user the "Follow" button should change to "Unfollow"

<img width="310" alt="image" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/78985396/482d52d2-375b-4639-8e1c-2633359e3452">

**Comment by sadikkuzu** [comment]
@aykutkantas hi,
Could you please fill the project detail card for this issue?
![image](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/23168063/7c371d5b-d195-4a2b-ac84-d155e4f95f39)

**Comment by aykutkantas** [comment]
done :) @sadikkuzu I have filled the project detail card also, thanks for reminder
