### ISSUE TITLE
Cache photo system in frontend

### ISSUE THREAD

**Issue by ckertam** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#83]
We need to cache user profile photos when we request them once. Such as in homepage for every story the system requests user photos. But if a user exists more than 1 it should only send a request 1 time.

**Comment by sadikkuzu** [comment]
Hi @dbaslan @aykutkantas
What is the latest situation of caching photos in frontend task?
Is there anything we can do to overcome possible blockages?
