### ISSUE TITLE
Add UML diagrams

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#84]
We need UML diagrams that illustrate the system's design and architecture for milestone 1. Will get them from Caner and add them to the wiki.

Due Date: 30 October

**Comment by ckertam** [comment]
I have low internet connection can you solve this? @dbaslan

**Comment by dbaslan** [comment]
[Diagram](https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Diagrams) added, will update it as we change the architecture, might add others as well. Closing.
