### ISSUE TITLE
Story like button does not work

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#85]
Story like button does not work properly. When click it like counter decreases instead of increase. 

<img width="831" alt="Screenshot 2023-10-29 at 15 59 11" src="https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/assets/126410955/33d5e333-4ba4-409e-9681-544c82ad52ab">

**Comment by ckertam** [comment]
Resolved by #95
