### ISSUE TITLE
Loading home page is too late

### ISSUE THREAD

**Issue by aykutkantas** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#86]
Loading home page takes too much times. Requires to fix it.

**Comment by aykutkantas** [comment]
Not only homepage, but also profile page is loaded lately. In local env it is very fast but in deploy it takes too much time. It seems related to deployment process.

**Comment by sadikkuzu** [comment]
@SWE574-Fall2023-Group1/backend team has done necessary actions to speed up the home page 🚀 

@aykutkantas Could you check again please?

**Comment by aykutkantas** [comment]
It looks so good, thanks team :)
