### ISSUE TITLE
Upload mockups directly to repo

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#87]
Our mockups are currently hyperlinked screenshots on the wiki. We should upload them directly as png files under the Documents folder in the repository, and link to them from the wiki.  @SWE574-Fall2023-Group1/frontend 

Due Date: 30 November

**Comment by sadikkuzu** [comment]
I think we may initially use wiki page as in mobile repo wiki:
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1-mobile/wiki/Mobile-Mock%E2%80%90Ups

**Comment by sadikkuzu** [comment]
Sorry, there have already been screenshots in G1 wiki 👍🏼 
https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/wiki/Mockups-and-Storyboards

**Comment by dbaslan** [comment]
Uploaded mobile mockups to repo.

**Comment by dbaslan** [comment]
Adjusted the links in the wiki to display the uploaded mockups, closing. Let's follow the same procedure for future mockups / design documents.
