### ISSUE TITLE
Prepare pre-release for milestone 1

### ISSUE THREAD

**Issue by dbaslan** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#92]
We need to make a pre-release on GitHub today, including an apk file of the mobile app, along with deployment instructions. I have copied the instructions below: 

* The software must be dockerized and deployed
* Create a pre-release version of your software that marks this version (check out how you create a </span><a href="https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases" target="_blank" rel="noopener"><span>release</span></a><span> in GitHub):</span>
* Release Name: 0.1.0-alpha (pre-release option)
* Release Description: Brief description of requirements that are covered
* Tag name: customer-milestone-1
* Your release should include the android package file .apk
* All instructions for building and running the software should be provided, including the docker build instructions and environment variables, if any. A fresh programmer that is fluent with various programming tools but not docker itself nor your project, should be able to do the deployment (for both web and mobile) by just following your steps.

**DUE DATE: 30.10.2023 17:00** as per the instructions

@SWE574-Fall2023-Group1/mobile  @SWE574-Fall2023-Group1/backend  @SWE574-Fall2023-Group1/devops 

I can take care of the requirements and formatting once the release is online.

**Comment by sadikkuzu** [comment]
@dbaslan mobile part is ok.
I will also this repo's pre-release.
(as soon as report is ready)

**Comment by dbaslan** [comment]
@sadikkuzu Thank you! Can you go ahead with the pre-release when you are available? I am currently finishing up the report, should not take longer than an hour, and the deadline for it is in four days so it is not as urgent as the software release.

**Comment by sadikkuzu** [comment]
Sure 👍🏼 

So, due date in the description will change, right?

**Comment by sadikkuzu** [comment]
Done 🚀 

https://github.com/SWE574-Fall2023-Group1/SWE574-Fall2023-G1/releases/tag/customer-milestone-1
